apiVersion: v1
name: secretsmanager-chart
description: A Helm chart for the ACK service controller for AWS Secrets Manager (SecretsManager)
version: 0.0.6
appVersion: 0.0.6
home: https://github.com/aws-controllers-k8s/secretsmanager-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/secretsmanager-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: SecretsManager Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/secretsmanager-maintainer
keywords:
  - aws
  - kubernetes
  - secretsmanager
